apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backstage-showcase-efnk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backstage-showcase-efnk
    app.kubernetes.io/part-of: backstage-showcase-1
  name: backstage-showcase-efnk
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: backstage-showcase-efnk
status:
  loadBalancer: {}
